Kan 44 kaleb
blissfulsaint/cse310team pull request #25
Opened 2023-10-17 19:16 UTC by LampofDiogenes

added free use image, and then referenced this image as a string in JSON

2023-10-17 19:42 UTC, blissfulsaint requested changes
Your file path just needs two dots before the first backslash, not three :)

2023-10-19 17:16 UTC, blissfulsaint approved these changes

2023-10-19 17:26 UTC, JaeleeJ approved these changes

2023-10-19 18:46 UTC, tyler953 approved these changes

2023-10-19 18:47 UTC, JacobHolst1 approved these changes

2023-10-19 19:01 UTC, tyler953 approved these changes

2023-10-19 19:03 UTC, blissfulsaint approved these changes

2023-10-19 19:07 UTC, closed without merging